spring:
  datasource:
    url: jdbc:h2:mem:test_mem
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: ture
    hibernate.ddl-auto: create

  h2.console:
    enabled: true
    path: /h2

  sql.init.mode: always
