name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build React & Spring Project
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: corretto

      - name: Build React Project
        env:
          CI: false
        run: |
          cd ./frontend
          npm install
          npm run build
          cd ../

      - name: Build Spring Project
        run: | 
          chmod +x ./back_end/gradlew
          ./back_end/gradlew build

      # Build & Push Docker Image
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker React Project Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/chirp_webserver:latest

      - name: Build and push Docker Spring Project Image
        uses: docker/build-push-action@v2
        with:
          context: ./back_end
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/chirp_applicationserver:latest
